### Generated by rprotoc. DO NOT EDIT!
### <proto file: xstream_pack.proto>
# 
# package apsara.odps.tunnel.proto;
# 
# message XStreamPack
# {
# 	required bytes pack_data = 1;
# 	optional bytes pack_meta = 2;
# }
require 'protobuf'
require 'protobuf/message'
require 'protobuf/enum'


module OdpsDatahub
  class XStreamPack < ::Protobuf::Message
    required :bytes, :pack_data, 1
    optional :bytes, :pack_meta, 2
  end
end